kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: chat-backend-canary
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: chat
        role: backend
        env: canary
    spec:
      containers:
      - name: backend
        image: ale55ander/backend:1.4
        env:
          - name: ALLOWED_ORIGIN
            value: "http://${FRONT_C_IP}:3000"
          - name: REDIS_ADDR
            value: "${REDIS_C_IP}:6379"
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        command: ["backend"]
        ports:
        - name: backend
          containerPort: 8080
