kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: chat-frontend-canary
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: chat
        role: frontend
        env: canary
    spec:
      containers:
      - name: frontend
        image: ale55ander/frontend:1.4
        env:
          - name: REACT_APP_BACKEND_WS
            value: "ws://${BACK_C_IP}:${BACK_NODE_PORT}"
          - name: REACT_APP_BACKEND_URL
            value: "http://${BACK_C_IP}:${BACK_NODE_PORT}"
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            port: 3000
        command: ["npm", "start"]
        ports:
        - name: frontend
          containerPort: 3000
