kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: chat-frontend-production
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: chat
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: ale55ander/frontend:1.4
        env:
          - name: REACT_APP_BACKEND_WS
            value: "ws://localhost:8080"
          - name: REACT_APP_BACKEND_URL
            value: "http://localhost:8080"
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
        command: ["npm", "start"]
        ports:
        - name: frontend
          containerPort: 3000
