master:
  installPlugins:
    - kubernetes:1.15.2
    - workflow-job:2.32
    - workflow-aggregator:2.6
    - workflow-multibranch:2.21
    - credentials-binding:1.18
    - git:3.9.4
    - github:1.29.4
    - pipeline-stage-view:2.11
    - cloudbees-bitbucket-branch-source:2.4.4
    - greenballs:1.15
  image: "jenkins/jenkins"
  imageTag: "lts"
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  servicePort: 8181
  serviceType: NodePort
  nodePort: 32000

agent:
  enabled: false

persistence:
  enabled: true
  mountDockerSocket: true
  existingClaim: jenkins-pvc
  volumes:
    - name: dockerbin
      namespace: cd-jenkins
      hostPath:
        path: /usr/bin/docker
  mounts:
    - name: dockerbin
      mountPath: /usr/bin/docker
networkPolicy:
  apiVersion: networking.k8s.io/v1
rbac:
  create: true
  serviceAccount.name: cd-jenkins
