apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: cd-jenkins
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/jenkins   
