master:
  installPlugins:
    - kubernetes:1.15.2
    - workflow-job:2.32
    - workflow-aggregator:2.6
    - workflow-multibranch:2.21
    - credentials-binding:1.18
    - git:3.9.4
    - github:1.29.4
    - pipeline-stage-view:2.11
    - cloudbees-bitbucket-branch-source:2.4.4
    - greenballs:1.15
  image: jenkins/jenkins
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  servicePort: 8181
  serviceType: NodePort
  nodePort: 32000
  # volumes:
  #   type: HostPath
  #   volumeName: docker-sock
  #   hostPath: /var/run/docker.sock
  #   mountPath: /var/run/docker.sock
  # volumes:
  #   type: HostPath
  #   volumeName: docker-bin
  #   hostPath: /usr/bin/docker
  #   mountPath: /usr/bin/docker
agent:
  enabled: true
  image: jenkins/jnlp-slave
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "600m"
      memory: "768Mi"
  volumes:
    - type: HostPath
      volumeName: docker-sock
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock
persistence:
  enabled: true
  existingClaim: jenkins-pvc
networkPolicy:
  apiVersion: networking.k8s.io/v1
rbac:
  create: true
  serviceAccount.name: cd-jenkins
