# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: chat-frontend-canary
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: chat
        role: frontend
        env: canary
    spec:
      containers:
      - name: frontend
        image: ale55ander/frontend:1.4
        env:
          - name: REACT_APP_BACKEND_WS
            value: "ws://localhost:8080"
          - name: REACT_APP_BACKEND_URL
            value: "http://localhost:8080"
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /frontend
            port: 3000
        command: ["npm", "start"]
        ports:
        - name: frontend
          containerPort: 3000
